### ISSUE TITLE
Pasting externally copied data can fail

### ISSUE THREAD

**Issue by thebearon** [CollaboraOnline/online#6597]
- Open the attached simple spreadsheet,
- Select A1:B300 (content is only text, nothing fancy),
- Copy, confirm copy to clipboard,
- Open a different spreadsheet, and paste into it.

[New spreadsheet.ods](https://github.com/CollaboraOnline/online/files/11718382/New.spreadsheet.ods)

=> If "some" criteria are met, pasting would not produce any results, and instead show the following error in browser console.

```
Clipboard.js:305 Uncaught TypeError: this.isPasteSpecialDialogOpen is not a function
    at Clipboard.js:305:16
    at request.onload (Clipboard.js:225:6)
```

I'm not sure what the criteria is exactly, but I could reproduce it when copying/pasting on an external test server, but not when both copying and pasting on a local instance. However, copying from the external server and pasting on the local instance triggered the bug as well.

This is a regression from e116a4d3e8cbfb5b673e212822a17992c506da50:
```
Author:     Gökay Şatır <gokaysatir@collabora.com>
AuthorDate: Thu Mar 2 12:27:03 2023 +0300
Commit:     Gökay Şatır <gokaysatir@gmail.com>
CommitDate: Fri Mar 3 11:38:33 2023 +0300

    Use a JSDialog for pasteSpecial dialog.
```
