### PR TITLE
Fix build & ignore test csv

### PR DESCRIPTION
**Pull request by eszkadev**
Fix build in UnitPerf
    
    ./common/Unit.hpp:488:18: error: 'UnitWSD::onDocumentLoaded' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
    
caused by commit 6e790c63d0997094979b2a237f428ef7706e62ef
feat: Changes to UnitPerf measuring

### CODE REVIEW

**Review by vmiklos — APPROVED** [review]
Looks good to me, thanks.

I just ran into this with my clang build as well.
