### ISSUE TITLE
23.05.1-3 can not build on libreoffice 7.5.4

### ISSUE THREAD

**Issue by hillwoodroc** [CollaboraOnline/online#6909]
I try to build online 23.05.1-3 on libreoffice 7.5.4, but I get the build failure. Can‘t CollaboraOnline be built on Libreoffice upstream code?

[   40s] kit/ChildSession.cpp:2540:22: error: 'LOK_CALLBACK_A11Y_FOCUS_CHANGED' was not declared in this scope; did you mean 'LOK_CALLBACK_CLIPBOARD_CHANGED'?
[   40s]  2540 |              type == LOK_CALLBACK_A11Y_FOCUS_CHANGED ||
[   40s]       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[   40s]       |                      LOK_CALLBACK_CLIPBOARD_CHANGED
[   40s]   CXX      net/HttpRequest.o
[   40s] kit/ChildSession.cpp:2541:22: error: 'LOK_CALLBACK_A11Y_CARET_CHANGED' was not declared in this scope; did you mean 'LOK_CALLBACK_STATE_CHANGED'?
[   40s]  2541 |              type == LOK_CALLBACK_A11Y_CARET_CHANGED ||
[   40s]       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[   40s]       |                      LOK_CALLBACK_STATE_CHANGED
[   40s] kit/Kit.cpp: In member function 'virtual void Document::trimIfInactive()':
[   40s] kit/Kit.cpp:981:17: error: 'using std::__shared_ptr_access<lok::Office, __gnu_cxx::_S_atomic, false, false>::element_type = class lok::Office' {aka 'class lok::Office'} has no member named 'trimMemory'
[   40s]   981 |         _loKit->trimMemory(4096);
[   40s]       |                 ^~~~~~~~~~
[   40s] kit/ChildSession.cpp:2542:22: error: 'LOK_CALLBACK_A11Y_TEXT_SELECTION_CHANGED' was not declared in this scope; did you mean 'LOK_CALLBACK_TEXT_SELECTION_END'?
[   40s]  2542 |              type == LOK_CALLBACK_A11Y_TEXT_SELECTION_CHANGED)
[   40s]       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[   40s]       |                      LOK_CALLBACK_TEXT_SELECTION_END
[   40s] kit/Kit.cpp: In static member function 'static void Document::ViewCallback(int, const char*, void*)':
[   40s] kit/Kit.cpp:1130:26: error: 'LOK_CALLBACK_DOCUMENT_PASSWORD_RESET' was not declared in this scope; did you mean 'LOK_CALLBACK_DOCUMENT_PASSWORD'?
[   40s]  1130 |         else if (type == LOK_CALLBACK_DOCUMENT_PASSWORD_RESET)
[   40s]       |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[   40s]       |                          LOK_CALLBACK_DOCUMENT_PASSWORD
[   40s] kit/ChildSession.cpp: In member function 'void ChildSession::loKitCallback(int, const std::string&)':
[   40s] kit/ChildSession.cpp:2938:10: error: 'LOK_CALLBACK_DOCUMENT_PASSWORD_RESET' was not declared in this scope; did you mean 'LOK_CALLBACK_DOCUMENT_PASSWORD'?
[   40s]  2938 |     case LOK_CALLBACK_DOCUMENT_PASSWORD_RESET:
[   40s]       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[   40s]       |          LOK_CALLBACK_DOCUMENT_PASSWORD
[   40s] kit/Kit.cpp:1146:26: error: 'LOK_CALLBACK_VIEW_RENDER_STATE' was not declared in this scope; did you mean 'LOK_CALLBACK_VIEW_CURSOR_VISIBLE'?
[   40s]  1146 |         else if (type == LOK_CALLBACK_VIEW_RENDER_STATE)
[   40s]       |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[   40s]       |                          LOK_CALLBACK_VIEW_CURSOR_VISIBLE
[   40s] kit/ChildSession.cpp:2968:10: error: 'LOK_CALLBACK_APPLICATION_BACKGROUND_COLOR' was not declared in this scope; did you mean 'LOK_CALLBACK_DOCUMENT_BACKGROUND_COLOR'?
[   40s]  2968 |     case LOK_CALLBACK_APPLICATION_BACKGROUND_COLOR:
[   40s]       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[   40s]       |          LOK_CALLBACK_DOCUMENT_BACKGROUND_COLOR
[   40s] kit/Kit.cpp: In member function 'std::shared_ptr<lok::Document> Document::load(const std::shared_ptr<ChildSession>&, const std::string&)':
[   40s] kit/Kit.cpp:1665:25: error: 'using std::__shared_ptr_access<lok::Document, __gnu_cxx::_S_atomic, false, false>::element_type = class lok::Document' {aka 'class lok::Document'} has no member named 'setViewTimezone'
[   40s]  1665 |         _loKitDocument->setViewTimezone(viewId, userTimezone.c_str());
[   40s]       |                         ^~~~~~~~~~~~~~~
[   40s] kit/Kit.cpp:1666:25: error: 'using std::__shared_ptr_access<lok::Document, __gnu_cxx::_S_atomic, false, false>::element_type = class lok::Document' {aka 'class lok::Document'} has no member named 'setAccessibilityState'
[   40s]  1666 |         _loKitDocument->setAccessibilityState(viewId, enableAccessibility);
[   40s]       |                         ^~~~~~~~~~~~~~~~~~~~~
[   40s] kit/ChildSession.cpp:3070:10: error: 'LOK_CALLBACK_A11Y_FOCUS_CHANGED' was not declared in this scope; did you mean 'LOK_CALLBACK_CLIPBOARD_CHANGED'?
[   40s]  3070 |     case LOK_CALLBACK_A11Y_FOCUS_CHANGED:
[   40s]       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[   40s]       |          LOK_CALLBACK_CLIPBOARD_CHANGED
[   40s]   CXX      net/HttpHelper.o
[   40s] kit/ChildSession.cpp:3075:10: error: 'LOK_CALLBACK_A11Y_CARET_CHANGED' was not declared in this scope; did you mean 'LOK_CALLBACK_STATE_CHANGED'?
[   40s]  3075 |     case LOK_CALLBACK_A11Y_CARET_CHANGED:
[   40s]       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[   40s]       |          LOK_CALLBACK_STATE_CHANGED
[   40s]   CXX      net/NetUtil.o
[   40s] kit/ChildSession.cpp:3080:10: error: 'LOK_CALLBACK_A11Y_TEXT_SELECTION_CHANGED' was not declared in this scope; did you mean 'LOK_CALLBACK_TEXT_SELECTION_END'?
[   40s]  3080 |     case LOK_CALLBACK_A11Y_TEXT_SELECTION_CHANGED:
[   40s]       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[   40s]       |          LOK_CALLBACK_TEXT_SELECTION_END
[   40s]   CXX      net/Socket.o
[   41s] kit/ChildSession.cpp:3085:10: error: 'LOK_CALLBACK_COLOR_PALETTES' was not declared in this scope; did you mean 'LOK_CALLBACK_TABLE_SELECTED'?
[   41s]  3085 |     case LOK_CALLBACK_COLOR_PALETTES:
[   41s]       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
[   41s]       |          LOK_CALLBACK_TABLE_SELECTED
[   41s]   CXX      wsd/Exceptions.o
[   41s]   CXX      net/Ssl.o
[   41s]   CXX      tools/mount.o
[   41s]   CXX      tools/coolstress-Stress.o
[   41s]   CXXLD    coolconvert
[   42s]   CXXLD    coolmap
[   42s]   CXXLD    coolmount
[   42s] make[2]: *** [Makefile:2767: kit/ChildSession.o] Error 1
[   42s] make[2]: *** Waiting for unfinished jobs....
[   43s] make[2]: *** [Makefile:2767: kit/Kit.o] Error 1

**Comment by gitgt** [comment]
This is a duplicate of #6881. Collabora Online 23.05 build on Collabora Office 23.05.
